### ISSUE TITLE
Araise moved from whatwedo/ to araise/ namespace

### ISSUE THREAD

**Issue by Ruesa18** [whatwedo/CronBundle#15]
The used stimulus controllers etc should be moved from `whatwedo/` to `araise/`

**Comment by tuxes3** [comment]
This bundle should not be used anymore. It should only be used in existing (old) projects. If you are using https://araise.dev , you should switch to using the [Symfony Scheduler](https://symfony.com/doc/current/scheduler.html). Feel free to reach out for any questions.
